Repository inevitable-dao/bento, pull requests merged in 2022-08, with the labels that each got.

#132 web: fix bugs in dependency arrays
  packages/bento-web/src/dashboard/DashboardPage.tsx
  packages/bento-web/src/dashboard/sections/IntroSection.tsx
  packages/bento-web/src/hooks/useWallets.ts
  packages/bento-web/src/profile/ProfileDetailPage/hooks/useProfile.ts
  packages/bento-web/src/profile/ProfileEditPage/ProfileEditPage.tsx
  packages/bento-web/src/profile/ProfileEditPage/components/ProfileLinkEditItem.tsx
Labels: bug

#136 web(landing): Add animations to header illusts and buttons
  packages/bento-web/public/assets/landing/header-illust.png
  packages/bento-web/public/assets/landing/header-illust@2x.png
  packages/bento-web/public/assets/landing/header-pawn.png
  packages/bento-web/public/assets/landing/header-pawn@2x.png
  packages/bento-web/src/landing/components/HeaderSection.tsx
Labels: status: dependent

#139 web(landing): Implement dashboard section of new landing page
  packages/bento-web/public/assets/icons/evmos.png
  packages/bento-web/public/assets/icons/optimism.png
  packages/bento-web/public/assets/landing/dashboard-card-clonex.png
  packages/bento-web/public/assets/landing/dashboard-card-clonex@2x.png
  packages/bento-web/public/assets/landing/dashboard-card-dai.png
  packages/bento-web/public/assets/landing/dashboard-card-dai@2x.png
  packages/bento-web/public/assets/landing/dashboard-card-ethereum.png
  packages/bento-web/public/assets/landing/dashboard-card-ethereum@2x.png
  packages/bento-web/public/assets/landing/dashboard-card-osmosis.png
  packages/bento-web/public/assets/landing/dashboard-card-osmosis@2x.png
  packages/bento-web/public/assets/landing/dashboard-card-tether.png
  packages/bento-web/public/assets/landing/dashboard-card-tether@2x.png
  packages/bento-web/public/assets/landing/dashboard-illust.png
  packages/bento-web/public/assets/landing/dashboard-illust@2x.png
  packages/bento-web/src/landing/LandingPage.tsx
  packages/bento-web/src/landing/components/DashboardSection.tsx
  packages/bento-web/src/landing/components/HeaderSection.tsx
Labels: status: dependent

#150 web(landing): fix font-family changing bug
  packages/bento-web/src/landing/LandingPage.tsx
Labels: bug

#148 web(profile): user information editor
  packages/bento-web/src/components/Button.tsx
  packages/bento-web/src/components/NavigationBar.tsx
  packages/bento-web/src/dashboard/DashboardPage.tsx
  packages/bento-web/src/profile/ProfileDetailPage/ProfileDetailPage.tsx
  packages/bento-web/src/profile/ProfileDetailPage/components/AssetSection.tsx
  packages/bento-web/src/profile/ProfileDetailPage/components/ProfileEditButton.tsx
  packages/bento-web/src/profile/ProfileDetailPage/components/ProfileEditor.tsx
  packages/bento-web/src/profile/ProfileDetailPage/components/ProfileLinkSection.tsx
  packages/bento-web/src/profile/ProfileDetailPage/components/ProfileViewer.tsx
  packages/bento-web/src/profile/ProfileDetailPage/components/QuestionSection.tsx
  packages/bento-web/src/profile/ProfileDetailPage/hooks/useProfile.ts
  packages/bento-web/src/profile/ProfileEditPage/ProfileEditPage.tsx
  packages/bento-web/src/profile/ProfileEditPage/components/Preview.tsx
  packages/bento-web/src/profile/components/FieldInput.tsx
  packages/bento-web/src/profile/components/LoginNudge.tsx
  packages/bento-web/src/profile/components/ProfileInstance.tsx
  packages/bento-web/src/recoil/profile.ts
  packages/bento-web/src/settings/SettingsPage.tsx
  packages/bento-web/src/utils/FeatureFlag.ts
Labels: help wanted
